project/loan/urls.py
from django.urls import path
from django.conf.urls import url

from loan import views

urlpatterns = [
    path(r'',views.home, name='home'),
    path(r'loan_request', views.loan_request, name='loan_request'),
    path(r'loan_admin', views.loan_admin, name='loan_admin'),
    # path(r'/loan_edit/(?P<loan_id>\d+)/', views.loan_edit, name='loan_edit'),
    # url(r'^accounts/login/$', auth_views.login, name='auth_login'),
    url(r'^loan_edit/(?P<loan_id>\d+)/$', views.loan_edit, name='loan_edit'),
    url(r'^ajax/validate_data/$', views.validate_data, name='validate_data'),
    url(r'^ajax/loan_delete/$', views.loan_delete, name='loan_delete'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path(r'admin/', admin.site.urls),
    # url(r'^accounts/login/$', auth_views.login, name='auth_login'),
    path(r'', include(('loan.urls', 'loan'), namespace='loan')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='auth_login'),

]

project/loan/models.py
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.

class Applicant(models.Model):
    GENDER_CHOICES = (
        (u'M', u'Masculino'),
        (u'F', u'Femenino'),
        (u'O', u'Otro'),
        (u'N', u'NS/NC'),
    )

    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    dni = models.PositiveIntegerField(validators=[MaxValueValidator(100000000)])
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES)
    email = models.CharField(max_length=100)


class Loan(models.Model):
    applicant = models.ForeignKey('loan.Applicant', on_delete=models.CASCADE)

    amount = models.DecimalField(decimal_places=2,
                                 max_digits=10,
                                 validators=[MinValueValidator(Decimal('0.00'))],
                                 null=True,
                                 blank=True)

    approved = models.NullBooleanField(default=None)

project/loan/forms.py
from django import forms
from loan.models import Loan, Applicant

class LoanForm(forms.Form):
    name = forms.CharField(label= 'Nombre')
    last_name = forms.CharField(label='Apellid')
    dni = forms.IntegerField(label='Nº document')
    gender = forms.ChoiceField(choices=Applicant.GENDER_CHOICES)
    email = forms.CharField(label='E-mail')
    amount = forms.DecimalField(label='Monto solicitado')



class EditLoanForm(LoanForm):
    TRUE_FALSE_CHOICES = (
        (True, 'Yes'),
        (False, 'No'),
        (None, 'En Espera')
    )

    approved = forms.ChoiceField(choices=TRUE_FALSE_CHOICES, label="Aprobado",
                                  initial='', widget=forms.Select(), required=True)

project/loan/views.py
import json

from decimal import Decimal

from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.core import serializers
from loan.forms import LoanForm, EditLoanForm
from loan.models import Loan, Applicant
from django.http import JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import requests


def home(request):
    template_name = 'home.html'
    return render(request, template_name=template_name)


def loan_request(request):
    template_name = 'request_loan.html'
    form = LoanForm()
    return render(request, template_name,
                  context={
                      'form': form,
                      'approved': False
                  })

@csrf_exempt
def validate_data(request):
    api_endpoint = 'http://scoringservice.moni.com.ar:7001/api/v1/scoring/'
    approved = False
    error = False
    if request.POST and request.is_ajax():
        form = LoanForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name', None)
            last_name = request.POST.get('last_name', None)
            dni = request.POST.get('dni', None)
            gender = request.POST.get('gender', None)
            email = request.POST.get('email', None)
            amount = request.POST.get('amount', None)
            data = {
                'name': name,
                'last_name': last_name,
                'document_number': dni,
                'gender': gender,
                'email': email,
                'amount': amount
            }
            response = requests.get(api_endpoint, params=data)
            context = response.json()
            approved = context.get('approved', None)
            error = context.get('error', None)
            try:
                applicant = Applicant.objects.create(
                    name=name,
                    last_name=last_name,
                    dni= dni,
                    gender=gender,
                    email=email
                )
                Loan.objects.create(
                    applicant=applicant,
                    amount=Decimal(float(amount)),
                    approved = approved
                )
            except Exception:
                approved = False
                error = True
    data = {
        'approved': approved,
        'error': error
    }
    return JsonResponse(data)


@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('auth_login'))
def loan_admin(request):
    template_name = 'loan_list.html'

    loan_list = Loan.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(loan_list, 10)

    try:
        loans = paginator.page(page)
    except PageNotAnInteger:
        loans = paginator.page(1)
    except EmptyPage:
        loans = paginator.page(paginator.num_pages)

    return render(request, template_name=template_name, context={'loan_list':loans})


@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('auth_login'))
def loan_edit(request, loan_id):
    template_name = 'edit_loan.html'
    loan = get_object_or_404(Loan,id=loan_id)
    form = EditLoanForm()
    print(request.method)
    if request.method == 'POST':
        print(request.POST.get('approved'))
        loan.approved = request.POST.get('approved')
        loan.amount = request.POST.get('amount')
        applicant = loan.applicant
        applicant.name = request.POST.get('name')
        applicant.last_name = request.POST.get('last_name')
        applicant.dni = request.POST.get('dni')
        applicant.gender = request.POST.get('gender')
        applicant.email = request.POST.get('email')
        applicant.save()
        loan.save()
        return HttpResponseRedirect('/loan_admin')
    elif request.method == 'GET':
        form.initial = {
            'name':loan.applicant.name,
            'last_name':loan.applicant.last_name,
            'dni':loan.applicant.dni,
            'gender':loan.applicant.gender,
            'email':loan.applicant.email,
            'amount':loan.amount,
            'approved': loan.approved
        }
    return render(request, template_name,
                  context={'form': form, 'loan': loan})


@csrf_exempt
@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('auth_login'))
def loan_delete(request):
    loan_id = None
    if request.POST and request.is_ajax():
        id = request.POST.get('id')
        try:
            loan = Loan.objects.get(id = id)
            loan_id = loan.id
            loan.delete()
        except Exception:
            loan_id = None
    data = {'id': loan_id}
    return JsonResponse(data)

project/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css'%}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css'%}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">

  <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <title>Moni</title>
</head>
<body>
<div>
  <div class="container">
    <div class="jumbotron header-container" style="background-color: lightblue">
      <a href="{% url 'loan:home' %}"><p class="text-right" style="color: black">Home.</p></a>
      <a href="{% url 'loan:loan_admin' %}"><p class="text-right" style="color: black">Sitio administrativo.</p></a>
      <a href="{% url 'loan:loan_request' %}"><p class="text-right" style="color: black">Solicitar prestamo.</p></a>
      <h1>Moni technical Test</h1>
    </div>
    {% block content %}
    {% endblock %}
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
{% block javascript %}{% endblock %}
</body>
</html>

project/templates/edit_loan.html
{% extends 'base.html' %}

{% block content %}
  <form method="POST" action="{% url 'loan:loan_edit' loan.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
  </form>

{% endblock %}

project/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

project/templates/loan_edit.html
{% extends 'base.html' %}

{% block content %}
ACA
{% endblock %}

project/templates/loan_list.html
{% extends 'base.html' %}


{% block javascript %}
  <script>
    $(".delete_button").click(function() {
      var id = $(this).attr('id');
      $.ajax({
        url : 'ajax/loan_delete/',
        type: 'post',
        data : {'id': id},
        data_type : 'json',
        success: function (data) {
          if (data.id !== null) {
            $('.stack'+data.id).html('')
          }
        },
        error : function (data) {
          alert(data)
        }

      })
    });
  </script>

{% endblock %}

{% block content %}
  <h2>Lista de prestamos</h2>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>id</th>
        <th>Solicitante</th>
        <th>Monto</th>
        <th>Estado</th>
        <th>Acciones</th>
      </tr>
    </thead>
  <tbody class="table_body">
    {% for loan in loan_list %}
      <tr class="stack{{ loan.id }}">
        <td>{{ loan.id }}</td>
        <td>
          {{ loan.applicant.name }}
          {{ loan.applicant.last_name }}
        <td> $ {{ loan.amount }}</td>
        <td>
          {% if loan.approved %}
            Aprobado
          {% elif loan.approved == None %}
            En espera
          {% else %}
            Desaprobado
          {% endif %}
        </td>
        <td style="width: 150px">
          <a class="btn btn-info btn-sm text-black-50" type="button"
             href="{% url 'loan:loan_edit' loan.id %}"> Editar </a>
          <a type="button"
                  class="delete_button btn btn-info btn-sm text-black-50"
                  id="{{ loan.id }}">
            <span class="glyphicon glyphicon-trash"></span> Delete
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
  {% if loan_list.has_other_pages %}
    <div >
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% if loan_list.has_previous %}
            <li><a href="?page={{ loan_list.previous_page_number }}">&laquo;</a></li>
          {% else %}
            <li class="disabled"><span>&laquo;</span></li>
          {% endif %}
          {% for i in loan_list.paginator.page_range %}
            {% if loan_list.number == i %}
              <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
              <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if loan_list.has_next %}
            <li><a href="?page={{ loan_list.next_page_number }}">&raquo;</a></li>
          {% else %}
            <li class="disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  {% endif %}

{% endblock %}

project/templates/request_loan.html
{% extends 'base.html' %}

{% block javascript %}
  <script>
    $('#submit-form').submit(function (e) {
      e.preventDefault();
      $.ajax({
        type: 'post',
        url: 'ajax/validate_data/',
        data_type: 'json',
        data: {
          name: $('#id_name').val(),
          last_name: $('#id_last_name').val(),
          dni: $('#id_dni').val(),
          gender: $('#id_gender').val(),
          email: $('#id_email').val(),
          amount: $('#id_amount').val()
        },
        success: function (data) {
          if (data.approved && !data.error) {
            $('#approved p').text("Aprobado");
            document.getElementById("submit-form").reset();
          } else if (data.error) {
            $('#approved p').text("Ha ocurrido un error, al procesa su pedido");
          } else {
            $('#approved p').text("Su pago fue Denegado");
          }

        },
        error: function (data) {
        }
      })
    });
  </script>
{% endblock %}


{% block content %}
<h1>Solicitud de prestamo</h1>
  <form method="POST" id="submit-form">
    {% csrf_token %}
    {{ form.as_p }}
      <input type="submit" value="Solicitar prestamo">
  </form>

  <div id="approved">
    <p></p>
  </div>

{% endblock %}